version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: ${PMA_CONTRAINER_NAME}
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: ${DB_PORT}
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - ${PMA_PORT}:80

  wordpress:
    depends_on:
      - db
    image: wordpress:6.0.1-php7.4-apache
    ports:
      - '${WP_PORT}:80'
    volumes:
      - './wordpress:/var/www/html'
      - './config/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini'
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:${DB_PORT}
      WORDPRESS_DB_USER: ${MYSQL_DATABASE}
      WORDPRESS_DB_PASSWORD: ${MYSQL_USER}
      WORDPRESS_DB_NAME: ${MYSQL_PASSWORD}

  wp-cli:
    image: wordpress:cli-2.6.0-php7.4
    depends_on:
      - wordpress
      - db
    environment:
      WORDPRESS_DB_HOST: db:${DB_PORT}
      WORDPRESS_DB_USER: ${MYSQL_DATABASE}
      WORDPRESS_DB_PASSWORD: ${MYSQL_USER}
      WORDPRESS_DB_NAME: ${MYSQL_PASSWORD}
    working_dir: /var/www/html
    volumes:
      - './wordpress:/var/www/html'
volumes:
  db_data: {}
